### ISSUE TITLE
Issues with exports

### ISSUE THREAD

**Issue by BinaryMuse** [primer/primer-primitives#2]
I was working with @ampinsk on using this module and we ran into a couple of issues:

First, while `primer-primitives` is importing the other modules here: https://github.com/primer/primer-primitives/blob/9ad6f7c7b8d7a982820146d4c1679af9124657a1/modules/primer-primitives/index.js#L1-L3

those modules aren't listed as dependencies in the `primer-primitives` `package.json`.

```
$ npm install --save primer-primitives
$ node
> require("primer-primitives")
Error: Cannot find module 'primer-colors'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

Secondly, the individual modules don't seem to be exporting their values correctly:

```
$ npm install --save primer-colors
$ node
> require("primer-colors")
Error: Cannot find module 'primer-colors'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

I believe this is because `package.json` for these modules specifies `index.js` as the package main, but the only file in the module is the `json` file with the definitions inside it.

**Comment by broccolini** [comment]
Thanks for the issue @BinaryMuse, sorry for not testing that initially, will fix!
